// app/layout.tsx
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { CartProvider } from "@/context/cartContext";
import "./globals.css";
import Navigation from "./components/Navigations";
import localFont from "next/font/local";
import Footer from "./components/Footer";
import ReactQueryProvider from "./providers/ReactQueryProvider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const kaizer = localFont({
  src: "../public/fonts/kaizer.ttf",
  display: "swap",
  variable: "--font-kaizer",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${kaizer.variable} font-montserrat antialiased`}
      >
        <ReactQueryProvider>
          <CartProvider>
            <Navigation />
            {children}
            <Footer />
          </CartProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
