import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { CartProvider } from "@/context/cartContext";
import "./globals.css";
import Navigation from "./components/Navigations";
import localFont from "next/font/local";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const kaizer = localFont({
  src: "../public/fonts/kaizer.ttf",
  display: "swap",
  variable: "--font-kaizer",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${kaizer.variable} antialiased`}>
        <CartProvider>
          <Navigation />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
